spring:
  datasource:
    password: root
    username: gAmd0610@digamo0708#
    url: 'jdbc:mysql://localhost:3306/microservice?useTimezone=true&serverTimezone=UTC'
  jpa:
    hibernate:
      ddl-auto: update
